[tool.poetry]
name = "mysite2"
version = "0.1.0"
description = ""
authors = ["Vfrid <113192881+Vfrid@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
